db_host: string
db_user: string
db_pass: string
db_port: 3306
# nombre de la DB segun se indic칩 en serverless.yml
db_name: WebinarMariaDB
# se compone un string que permite tener el identificador unico de los recursos de tipo
# funciones dentro del proyecto.  con esto podemos referir el proyecto hacia las
# funciones lambda que declaremos.  posteriormente solo se deber치 llamar la referencia
# al prefijo, a침adiendo luego solo el nombre de la funci칩n.
arn_prefix: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}