db_host: ww1l8s1mjibrav8.cmvhpzzezajb.us-east-2.rds.amazonaws.com
db_user: cartulina
db_pass: 20202021
db_port: 3306
db_name: WebinarMariaDB
arn_prefix: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}